version: "3.8"
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        REACT_APP_SUPABASE_URL: ${REACT_APP_SUPABASE_URL}
        REACT_APP_SUPABASE_ANON_KEY: ${REACT_APP_SUPABASE_ANON_KEY}
        REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL}

    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
